### ISSUE TITLE
Be able to insert bound parameters into queries

### ISSUE THREAD

**Issue by virgs** [guilhermecorsino/enqueuer-plugin-anydb#3]
```
  - publishers:
      - type: anyDb
        options: <<options>>
        query: INSERT INTO table_sample VALUES (?, ?);
        params:
         - "'Virgs'"
         - 29
        onQueryCompleted:
          assertions:
            - expect: rowCount
              toBeEqualTo: 1
```
